# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3492c09057d969cefb5d73b2aed6dc32c862a7dde295a2af345347bb1060c1bfb54d6cb068adfe7762b17332546594725ee31e1bc4a851f3e888fdb6c3bfd9f0

test:
  secret_key_base: 5a7452f1c3b0c146ff874c9d4be7cb67004c31be264d3760080fea349be6e2573d8b9efaa7ecee7d4e53b8ad58bff604945f0fc7ad5ddee229045bf5654baefe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
